apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "pose-estimation-web.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pose-estimation-web.name" . }}
    helm.sh/chart: {{ include "pose-estimation-web.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pose-estimation-web.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pose-estimation-web.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "pose-estimation-web.fullname" . }}
      containers:
        {{- if .Values.develop.enabled}}
        - name: {{ .Chart.Name }}-dev
          image: "{{ .Values.develop.repository }}:{{ .Values.develop.tag }}"
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              subPath: nginx.conf
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if not .Values.develop.enabled }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
