apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pose-estimation-web.fullname" . }}
data:
  nginx.conf: |
    worker_processes  32;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
    worker_connections  65536;  ## Default: 1024
    }

    http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    sendfile     on;
    tcp_nopush   on;
    server_names_hash_bucket_size 128;
    send_timeout 10;
    gzip on;

    server {
        listen       80;
        server_name  pose-estimation-web;

        location /videostream.cgi {
          {{- with .Values.cam }}
          set $args {{ printf "user=%s&pwd=%s" .user .pwd }};
          proxy_pass {{ .url }};
          {{- end }}
        }
        
        {{- if .Values.develop.enabled}}
        location / {
          proxy_pass      http://localhost:3000;
        }
        {{- else }}

        root /app/build;
        location / {
          try_files $uri $uri/ @rewrites;
        }

        location @rewrites {
          rewrite ^(.+)$ /index.html last;
        }

        location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
          expires max;
          add_header Pragma public;
          add_header Cache-Control "public, must-revalidate, proxy-revalidate";
        }
        {{- end }}
    }
    }